### ISSUE TITLE
Feature request: pop_front, pop_front_range

### ISSUE THREAD

**Issue by tmplt** [bitvecto-rs/bitvec#111]
I've just replaced `VecDequeue` with `BitVec` for a crate where I need to decode a bitstream and handle cases where words are no longer aligned to bytes. `BitVec` simplifed the code a ton. But I want to pop bits from the front (currently possible via `bv.rotate_left(1); bv.pop()`, from #38) but also bytes. For the latter I use

```rust
            let byte = self.incoming[0..=7].load::<u8>();
            self.incoming = self.incoming[8..].into();
```

but I'm unsure if any copies are made here. In #38 you have already expressed plans to add a `pop_front`. Could some `pop_front_range` (or similar) be added so that words or arbitrary sizes can be trivially extracted from a bitstream?

**Comment by tmplt** [comment]
I found that a more performant solution in this use-case is to reverse the incoming bitstream so that `pop` gets me the data I want without the expensive rotations. See https://github.com/tmplt/itm-decode/commit/6f9c89ec4c049bcc5cbba9d30af4aa067919c227.

I no longer need the requested features. Feel free to close.

**Comment by myrrlyn** [comment]
You're right that rotation is non-trivially expensive.

I would suspect that `.drain(.. idx)` is probably a faster way to remove a range of bits from the front at the moment, but `Drain`'s destructor that actually performs the move is *also* non-trivially complex.

I'll compare `.drain(.. idx)` against a `.remove_front(idx)` that shunts `[idx ..]` to `[0 .. len - idx]` and truncates; if it's significantly faster, I'll add a method, otherwise I'll add to the docs that `.drain()` can accomplish this task.
