### ISSUE TITLE
no easy way to convert bitslice to usize

### ISSUE THREAD

**Issue by seanyoung** [bitvecto-rs/bitvec#119]
I have some code which needs to iterate over a bitvec, by 1, 2, 4, or 16 bits (using chunks). Those 1, 2, 4, or 16 bits needs to be converted back to a numeric value, but bitvec does not seem to have a way to do this.

For now I have this function: https://github.com/seanyoung/ir-ctl/blob/40369f3aac103a72349c0c3b06208da8f92573d5/irp/src/render.rs#L519-L529

```
fn bit_to_usize(bit: &BitSlice) -> usize {
    let mut v = 0;

    for i in 0..bit.len() {
        if bit[i] {
            v |= 1 << (bit.len() - 1 - i);
        }
    }

    v
}
```

This is not very efficient. It would be nice if bitvec offered an builtin way of doing this; surely this can be done without looping at all.

**Comment by myrrlyn** [comment]
## API

The simplest solution is probably to use [`.clone_from_bitslice()`] or [`.copy_from_bitslice()`].

```rust
let mut v = 0usize;
v.view_bits_mut::<Lsb0>()[.. bit.len()].clone_from_bitslice(bit);
v
```

I am assuming here that you are using the default type parameters of `<Lsb0, usize>` (`LocalBits` on little-endian machines aliases to `Lsb0`). The `.copy_from_bitslice` method requires exactly-matching type parameters in order to function.

Automatic batch-element loads like this only work when the type parameters match up. There is a general solution, but its correctness relies on the manner in which you populate the source `&mut BitSlice` from which `bit` is derived.

The [`BitField`] trait provides methods to [`.store()`] values into a `BitSlice`, and then [`.load()`] them back out. These do not require that the storage type parameter of a `BitSlice` match the value being transferred into/out of it, so you can store/load a `usize` in any `&mut BitSlice<O, T>`. However, the batch-loading behavior of the provided implementations do not attempt to maintain equivalence with the behavior you would get from `dest.clone_from_bitslice(src.view_bits())`.

*This can have surprising effects*

`BitField` implementations are guaranteed to always be the fastest possible means of transferring integer values into or out of a bit-slice. However, this speed comes at the cost of losing the iteration equivalence. If you are populating the bit-slice by walking its indices, you need to use the `.clone_from_bitslice()` or `.copy_from_bitslice()` methods to ensure that your output remains semantically correct. These will attempt to use `BitField` batch loading under the hood where doing so is known to remain correct, and must fall back to the bitwise crawl you used if the types do not match up.

## Implementation

In your provided implementation, a bit-slice which contains the four symbols in semantic order `[W, X, Y, Z]` will produce a `usize` with the bit-pattern `0bWXYZ`. However, an `&BitSlice<LocalBits, _>` will, when `LocalBits` aliases to `Lsb0`, contain the bit-pattern `0bZYXW`.

If you require that the source bitstream write to the destination value in `Msb0` order, then you will need to use

```rust
v.view_bits_mut::<Msb0>()[usize::BITS as usize - bit.len() ..].clone_from_bitslice(bit);
```

and note that this implementation will be a bitwise crawl.

The specific answer you use depends on your use case with the value being populated and the means by which the bitstream is populated. `BitField` is fast but behaves surprisingly when the storage `BitSlice` crosses an element boundary; `.clone_from_bitslice()` is potentially slower but always correct.

At an *absolute worst case*, you can use the fact that `.iter_mut()` produces pseudo-`&mut bool` references, and you can use iteration to ensure that the output is structured exactly as you need it to be.

```rust
let mut v = 0usize;
for (mut dst, src) in 
  v.view_bits_mut::<Lsb0>()
    [.. bit.len()]
    .iter_mut()
    .zip(bit.iter().rev()) 
{
  dst.set(*src);
}
```

or similar constructs can get you there. This is a last resort if you are not able to use either the transfer methods or `BitField` trait methods to accomplish what you need.

[`BitField`]: https://docs.rs/bitvec/0.22.1/bitvec/field/trait.BitField.html
[`.clone_from_bitslice()`]: https://docs.rs/bitvec/0.22.1/bitvec/slice/struct.BitSlice.html#method.clone_from_bitslice
[`.copy_from_bitslice()`]: https://docs.rs/bitvec/0.22.1/bitvec/slice/struct.BitSlice.html#method.copy_from_bitslice
[`.load()`]: https://docs.rs/bitvec/0.22.1/bitvec/field/trait.BitField.html#tymethod.load
[`.store()`]: https://docs.rs/bitvec/0.22.1/bitvec/field/trait.BitField.html#tymethod.store

**Comment by seanyoung** [comment]
Thank you very much, that's super helpful.

The first option doesn't work for me. It reproduces incorrect results.

So the underlying `BitVec` gets populated with all sorts of odd sizes. For example, we add 7 bits, then 1 bit, and then we may attempt to iterate over two bit chunks, and then get the usize (value?) from the bitslice from the iteration. Note that the iteration will always be over 1, 2, 4, or 16 bits, so if the bits are packed in tightly then no bitslice should straddle two elements.

The second option which iterates over the bits does work, but seems less than ideal.

Would it be useful to have a small testcase?
