### ISSUE TITLE
Possible panic in public function mem::elts<T>

### ISSUE THREAD

**Issue by lizhuohua** [bitvecto-rs/bitvec#123]
Hi. When `T` is a zero-sized type, function `mem::elts<T>` would panic because of the remainder operation `bits % width`.

Probably this function should have private visibility if it is not intended to be exposed to users.

**Comment by myrrlyn** [comment]
This is required to have `pub` visibility so that it can be used in macros. It is not public API, as evinced by `#[doc(hidden)]`.

`const fn`s cannot take trait bounds at this time; this function is only called on non-ZST types, so I have never added checks for ZST behavior. However, since `const fn` supports branching, I am able to add a check to avoid computations on ZST. As a compile-time check, adding such a branch imposes no cost and is therefore the right thing to do.
