### ISSUE TITLE
Allow custom allocator for BitVec and BitBox

### ISSUE THREAD

**Issue by Andful** [bitvecto-rs/bitvec#131]
Similarly to how `std::boxed::Box` and `std::vec::Vec` allow for custom allocators, it would be nice if `BitVec` and `BitBox` would allow for custom allocators.

**Comment by myrrlyn** [comment]
I am currently committed to operating on the stable release series. The blockers for `bitvec` adopting this API are:

- [`core::alloc::Allocator`](https://doc.rust-lang.org/core/alloc/trait.Allocator.html) is [unstable](https://github.com/rust-lang/rust/issues/32838)
- [`alloc::alloc::GlobalAlloc`](https://doc.rust-lang.org/alloc/alloc/struct.Global.html) is unstable (same issue)
- `Vec<T, A>` and `Box<T, A>` have stabilized their *signature*, but have not stabilized the types used to instantiate the `Vec<T>` and `Box<T>` half-formed types.

Therefore, once rust-lang/rust#32838 completes, the `allocator_api` feature is stabilized, *and* these items are no longer gated by it, `bitvec` will soon thereäfter raise its MSRV to the Rust release that did this and add the `A: Allocator` type parameter to `BitBox` and `BitVec`.

Following `alloc`'s lead, this can likely be done in a minor version, since `BitVec<T, O>` is equivalent to `BitVec<T, O, GlobalAlloc>`.

I am not currently willing to offer a `feature = "nightly"` gate, due to the maintenance costs this would impose on the crate.

**Comment by myrrlyn** [comment]
Since I plan to do this immediately upon stabilization in the standard library, I am going to close *this issue*. It is not a dismissal, just no longer a work item I am not tracking myself. Thank you for the request, though.
