### ISSUE TITLE
Usage in const fns.

### ISSUE THREAD

**Issue by vi** [bitvecto-rs/bitvec#137]
Should `bitvec::array::BitArray::new` and other such functions be `const fn`s?

Is `bitvec` appropriate crate to use in const-heavy no_std no_alloc environment?

**Comment by myrrlyn** [comment]
Summary: Yes it is: use either `bitarr![const ...]` or `BitArray{}` literals to create your buffer in `const` contexts, then use the crate normally to operate on the buffer in non-`const` contexts. It is built for use in no-alloc environments and will work correctly there; it is simply unable to do most of its work *in `const` position*.

----

The crate cannot be made `const fn` until `const fn` allows more traits than `Sized` to be used in bounds.

This is something that I have wanted for a long time, and has been brought up as a reason that people who have wanted to use it have chosen against. Unfortunately, the parametricity over ordering and register width is equally important to other users of the crate, myself included, and so I am not willing to remove it, especially since this is a compiler limitation that may be removed in the future.

I have compromised on `BitArray` in particular: it is a fully public data struct, so you *are* able to construct literals of it in `const` contexts with `BitArray<O, T> { data: a_const_expr(), _ord: MyOrdLiteral }`. The other two containers, `BitBox` and `BitVec`, definitionally require a heap allocation and as such are not meaningfully `const`-constructible.

Also note that the `bitarr![]` and `bits![]` macros **are** `const`-compatible! `bitarr![const ARGS...]` guarantees the production of a `const`-evaluable expression, and `bits![static ARGS...]` produces a `static` binding that, definitionally, must be initialized with a `const` expression. This *only works* with the three bit-orderings that `bitvec` provides; if you have a custom ordering (which I have never seen anyone actually do), it is ineligible for `const` production.

These are the extents of the compile-time buffer construction that can be done with the crate. *However*, both `BitSlice` and `BitArray` have no requirements on a dynamic allocator, and are equally usable in all three environments: `core`-only, `core`+`alloc`, and `std`. While my ability to *create* a bit-buffer in `const` contexts is limited, you are able to *operate* on a bit-buffer at run-time without any reliance on the environment.

Observationally, a great deal of `bitvec`'s overhead (creating a `&BitSlice` view, or addressing particular bits within a buffer) is solved at compile time *after* `const` evaluation is complete. I am not able to provide any guarantees about this, either personally or within the codebase, due to limitations in the Rust source language, but I write it to be as understandable as possible to LLVM and have seen good results come of this.

**Comment by myrrlyn** [comment]
I am watching the compiler's `const fn` capabilities, in particular w.r.t. traits, myself and will add support as soon as it stabilizes. Until then, this is the limitation of my const support, so I am closing this. Thank you for the question; I hope my answer was useful to you.
