### ISSUE TITLE
Setting a bit without fetching

### ISSUE THREAD

**Issue by 3miliano** [bitvecto-rs/bitvec#138]
I am having trouble finding the right function that will let me set a bit without fetching the current value first. I know I can do it without using `bitvec` but I rather have a consistent interface for all my bit manipulation. 

There are registers such as [ISER](https://developer.arm.com/documentation/dui0552/a/cortex-m3-peripherals/nested-vectored-interrupt-controller/interrupt-set-enable-registers?lang=en) ARM that are used to trigger an action, like for example `enable an interrupt` in which the register only cares about the active bits and if we set them to 0 the current value of the register does not change. Effectively `AND`ing the whole write operation. 

From what I can tell from looking at the source code, the `set` method does a `fetch_and` or `fetch_or` depending on the value being set. In short, my question would be how can I set a value without fetching it first.

**Comment by myrrlyn** [comment]
There are no portable intrinsics for directly writing to an individual bit within a location. While many architectures do provide such an instruction, using it requires both compile-time *and run-time* detection of the target CPU. As such, I have chosen not to attempt to specialize its behavior in source code, and rely instead on the register-level read-modify-write behavior that is universally available.

Examples of processor support include:

- [`PDEP` and `PEXT`](https://en.wikipedia.org/wiki/X86_Bit_manipulation_instruction_set) in x86's BMI2
- [`BFI` and `BFC`](https://developer.arm.com/documentation/dui0552/a/the-cortex-m3-instruction-set/bitfield-instructions/bfc-and-bfi) in some(?) ARM architectures, including the M3 that you linked

Processor control registers are weird, and do not behave according to the standard rules that memory banks provide.

In this instance, the documentation suggests that `ISER` behaves as an implicit OR gate with the memory value written into it: for each bit of `ISER`, the corresponding bit in the memory value being stored either *does not affect it* (when storing a `0` bit) or unconditionally sets it (when storing a `1` bit). This has its counterpart in the [`ICER`](https://developer.arm.com/documentation/dui0552/a/cortex-m3-peripherals/nested-vectored-interrupt-controller/interrupt-clear-enable-registers?lang=en) register, which appears to have the same behavior: storing a `0` bit does not affect the corresponding interrupt, and storing a `1` bit unconditionally disables the corresponding interrupt.

The processor implements this behavior in silicon in order to provide a workaround for the fact that, by and large, embedded-software programmers use whole-register memory stores, and compilers *tend not to emit single-bit read/write instructions*.

As such, I suspect that `bitvec` would behave correctly when interacting with these registers. The registers are not documented as being clear-on-write, and are documented as ignoring the `0` bits of a written value, so a read-modify-write cycle should still produce the correct behavior.

**HOWEVER**: you *should not* use `bitvec` to perform modifications against memory-mapped control registers. It will *probably* work fine, but I *only* provide guarantees about `bitvec`'s behavior in the memory model of the Abstract Machine on which the Rust compiler and LLVM operate. The crate source code *does not* attempt to provide stronger behavioral guarantees about the actual behavior of the memory bus, and this distinction tends to start mattering when working with memory maps!

The problem with memory maps is that, essentially, they are always aliased (so you can only type references to them as `&Cell<u32>`, **not `&/mut u32`**), and they are always shared across independent executors (which means you actually need `UnsafeCell`, not `Cell`) but are not part of the processor cache system, so you don't need (and shouldn't use) atomic instructions.

The **most correct thing to do** is to use the [`voladdress`](https://docs.rs/voladdress/latest/voladdress) crate to perform your actual transactions against the memory bus. It always uses the `ptr::{read,write}_volatile` intrinsics, which correctly communicate to the compilers what is happening here. You should then use `bitvec` to operate solely on the stack temporary that either just came from, or is about to be sent into, the volatile memory access.

----

So to answer your actual question:

- `bitvec` does not now, and will not in the future, attempt to codegen a `bfi` instruction. You can write a function that does so yourself, but

to answer the questions I am blithely *assuming* you have, with the context that my job in 2020 and 2021 was to write ARM operational firmware that interacted with these registers:

- you probably don't need it; the documentation here, and the behavior I have observed doing this work myself in the past year, indicates that ARM registers are intended for whole-register reads/writes (and might actually *not* work with `bfi?` But I haven't attempted it), and furthermore
- `bitvec` has very limited support for the volatile operations necessary to correctly interact with MMIO regions, and does not guarantee correct behavior when used on them. If you need strict behavioral guarantees, use `voladdr` on the MMIO region and `bitvec` only on pure RAM.

**Comment by myrrlyn** [comment]
I am closing this as I am unable to add bit-level write-only operations using the tools available to me in the stable standard library. I hope my prior comment is useful to you, and I will be adding it to my documentation going forward. Thank you for the question!
