### ISSUE TITLE
WebAssembly deserialization error

### ISSUE THREAD

**Issue by alethes** [bitvecto-rs/bitvec#140]
I've encountered an issue with `BitVec` deserialization in an app compiled to WebAssembly. I'm getting the following serde error when deserializing a struct containing `BitVec`s:
```
Custom(
    "invalid value: integer `36024398987935680`, expected usize",
)
```
The issue doesn't occur when I remove `BitVec`s from the serialized struct. Deserialization in a natively compiled binary works fine. I'm guessing this is because of WebAssembly being a 32-bit environment, whereas the data is serialized in a 64-bit environment. I wonder if there's an easy way to safeguard against this. I've tried replacing some `usize`s with `u64`s in `serdes.rs` but as of yet without success.

**Comment by myrrlyn** [comment]
My `serde` support currently depends very strongly on deserializing into exactly the same environment that serialized it. This is not well documented, because I wrote it a while ago and have not had much time to actually use it. In particular, `usize` does not round trip across systems of different word widths.

Try changing your type definitions from `BitVec` to `BitVec<Lsb0, u32>`. 

If this works, you can also try using `BitVec<Lsb0, u64>`, but I don't know *offhand* if this will succeed in `x86_64 -> WASM`.

----

Alternatively, if you are transporting *only* the bit-buffer and are not embedding it in a larger structure, you might prefer to route completely through octet-streams. If you have `std::io::{Read,Write}` available, you should be able to use them to round-trip a bit-buffer. If you don't, you can go `BitVec -> Vec<u8> -> BitVec` with these:

```rust
use bitvec::prelude::*;

let bv: BitVec = whatever();
let v: Vec<u8> = bv.chunks(8).map(BitField::load_le::<u8>).collect();

let mut bv2 = BitVec::repeat(false, bv.len());
for (slot, byte) in bv2.chunks_mut(8).zip(v.into_iter()) {
  slot.store_le(byte);
}
```

This ought to round-trip correctly, even if the source and destination environments differ.

----

In all cases, you'll need to ensure that the source and destination *`BitVec<O, T>` types* are exactly identical, or else things start behaving very strangely. The only way to survive changing type parameters, including `BitVec<O, usize>` on differently-wide machines, is to use `[bool]` as your intermediate format.

**Comment by alethes** [comment]
Thanks a lot!

**Comment by elichai** [comment]
@myrrlyn I just stumbled on this now, will you be open to filing a fix that makes the serialization platform-independent?
