### ISSUE TITLE
bitarr! macro breaks compilation unless BitStore is imported

### ISSUE THREAD

**Issue by hwjsnc** [bitvecto-rs/bitvec#149]
Consider the following code:

```
extern crate bitvec;
fn main() {
    let _ = bitvec::bitarr![0; 256];
}
```

As of bitvec version 0.22.3, this (unexpectedly) does not compile, producing the following error message instead:

```
   Compiling bitarrtest v0.1.0 (/home/user/bitarrtest)
error[E0433]: failed to resolve: use of undeclared type `BitStore`
 --> src/main.rs:3:13
  |
3 |     let _ = bitvec::bitarr![0; 256];
  |             ^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared type `BitStore`
  |
  = note: this error originates in the macro `$crate::__extend_bool` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0433`.
error: could not compile `bitarrtest` due to previous error
```

In contrast, the following works as expected:

```
extern crate bitvec;
use bitvec::store::BitStore;
fn main() {
    let _ = bitvec::bitarr![0; 256];
}
```

**Comment by myrrlyn** [comment]
I try to ensure that I use fully-qualified paths everywhere in my macro implementations, but as you can clearly see, I am not perfect, and there's no lint for unqualified symbol names. My tests all import the prelude so that I can write them conveniently, and this completely slipped past.

The v1 rewrite appears to completely use fully-qualified symbol names (it certainly passes *this* test). I currently expect to release 1.0.0 on 2022 Jan 11, and I would encourage you to try its release candidates as I issue them. I would like to stop supporting the v0 development series now that v1 is in sight.

Since this is a minor fault on my part, and has a simple solution (import the symbol), I do not currently plan to issue a patch release that covers it. However, as I am working through my issue backlog, if a `0.22.4` patch *does* become necessary, I will include this in it.

Otherwise, I will close this once 1.0.0 is fully published.

Thank you again for the issue. I appreciate the consideration and always welcome defect reports.

**Comment by zheland** [comment]
There is a similar problem when using `bits`, `bitbox`, `bitvec` macros and when defining a bitarray via a list of elements using `bits`, `bitarr`, `bitbox`, `bitvec` macros:
```rust
fn main() {
    let _ = bitvec::bits![0; 256]; // error[E0433]: failed to resolve: use of undeclared type `BitStore`
    let _ = bitvec::bitarr![0; 256]; // error[E0433]: failed to resolve: use of undeclared type `BitStore`
    let _ = bitvec::bitbox![0; 256]; // ok
    let _ = bitvec::bitvec![0; 256]; // ok
    let _ = bitvec::bits![0, 1, 0]; // error[E0412]: cannot find type `Lsb0` in this scope
    let _ = bitvec::bitarr![0, 1, 0]; // error[E0412]: cannot find type `Lsb0` in this scope
    let _ = bitvec::bitbox![0, 1, 0]; // error[E0412]: cannot find type `Lsb0` in this scope
    let _ = bitvec::bitvec![0, 1, 0]; // error[E0412]: cannot find type `Lsb0` in this scope
}
```
https://github.com/bitvecto-rs/bitvec/blob/7176242b1032296cb4627d02cfb310ddd82b7839/src/macros.rs#L491
https://github.com/bitvecto-rs/bitvec/blob/7176242b1032296cb4627d02cfb310ddd82b7839/src/macros.rs#L245
https://github.com/bitvecto-rs/bitvec/blob/7176242b1032296cb4627d02cfb310ddd82b7839/src/macros/internal.rs#L339

**Comment by myrrlyn** [comment]
I'm going to close this as "absent in 1.0", and I'm trying to track what work I still need to do for that release. However, this is not a dismissal; please re-open later in the month if you are unable or unwilling to migrate off 0.22 and I have not issued a patch yet. Thank you again for the report.
