### ISSUE TITLE
More ones/zeros than specified, BitArray

### ISSUE THREAD

**Issue by Sagebati** [bitvecto-rs/bitvec#159]
This test fails: 

```
#[test]
    fn bitarray() {
        let x = bitarr!(1; 361);
        dbg!(x.iter_ones().filter(|&x| x > 361 ).collect::<Vec<_>>());
        assert_eq!(x.count_ones(), 361);
        assert!(!x.iter_ones().any(|x| x > 361))
    }
```

Why it's unexpected ?

I initialize an array of bits of length 361 with 1. The count is superior to the number of ones specified.
```
Left:  384
Right: 361
```

I don't know if it's a feature, feel free to close it, if it is.

**Comment by myrrlyn** [comment]
The current implementation of const generics does not allow me to create an array of 361 bits. This will [eventually change](https://docs.rs/bitvec/1.0.0/bitvec/array/struct.BitArray.html#future-api-changes) but until the language advances, I can't do anything about this.

The implementation of the `bitarr![BIT; COUNT]` value constructor repeats `BIT` for its entire memory content: `bitarr![1; 2]` produces `BitArray<_, _> { _ord: PhantomData, data: [!0; 1] }`. And, because `BitArray` always rounds up, you wind up with more bits than were requested.

For this reason, `BitArray`s that don't semantically fill their entire buffer will need to be wrapped in code that correctly subslices down to what you asked for. This can only be done with borrowed views at the time, so `&your_array[.. 361]` will produce a `&BitSlice` with 361 bits instead of 384.

Changing this behavior would currently require storing an additional `usize` length counter in-line with the bit-array, which renders it representationally incompatible with its storage buffer and therefore cannot implement the standard-library's array API. I elected to preserve representation compatibility at the cost of always rounding up the length, with a note that this will *eventually* change but must currently be handled manually by users.

**Comment by eggyal** [comment]
From the linked API docs:

> Exact bit lengths cannot be encoded into the `BitArray` type until the const-generics system in the compiler can allow type-level computation on type integers.

Sorry to hijack this (closed) issue, but would it be possible elaborate on this a smidge?  It's not immediately obvious why "type-level computation on type integers" is necessary; even if it, perhaps the typenum crate can provide an intermediate solution?

**Comment by eggyal** [comment]
I had a play with typenum, and got fixed-size `BitArray`s working in [a WIP branch](https://github.com/eggyal/bitvec/tree/issue-159).  Given that type-level computation on const generics probably won't land for some time, would such a typenum-based solution be of any interest in this crate?  Perhaps an interim v2 before the ultimate const generic solution eventually gets us to v3?

Tagging @myrrlyn just in case you don't otherwise see notifications on closed issues.
