### ISSUE TITLE
Broken docs links

### ISSUE THREAD

**Issue by Kylebrown9** [bitvecto-rs/bitvec#161]
The docs for [`Lsb0`](https://docs.rs/bitvec/latest/bitvec/order/struct.Lsb0.html) and [`Msb0`](https://docs.rs/bitvec/latest/bitvec/order/struct.Msb0.html) refer to "[a chapter](https://bitvecto-rs.github.io/bitvec/bit-ordering) with more detailed information on the memory representation this produces".

The link does not go to an existing page, and may be intended to refer to
https://bitvecto-rs.github.io/bitvec/type-parameters/bitorder.html

**Comment by myrrlyn** [comment]
Thanks. It's hard to keep track of all my cross links and I'm disappointed but not surprised I missed this one, especially since I rewrote the guide *after* the API docs.

It'll be fixed in the next patch release; in the mean time, the correct destination is <https://bitvecto-rs.github.io/bitvec/memory-representation>

**Comment by myrrlyn** [comment]
fixed in 1.0.1
