### ISSUE TITLE
[Question] bitvec without padding

### ISSUE THREAD

**Issue by danieleades** [bitvecto-rs/bitvec#163]
sorry, this is more a question than an issue, though I see the 'discussions' is not enabled.

cross-posted to https://stackoverflow.com/questions/71193952/convert-an-integer-to-a-minimally-padded-vector-of-bits-probably-using-bitvec

I'm trying to create compact binary representations of integers, without padding. I'm wondering the best way to achieve this with your crate? I'm actually putting together a simple arithmetic encoding scheme for lossy encoding of floats and integers. For that I need to do the following

- truncate and scale input values to an unsigned integer value (not relevant to this crate)
- generate the most compact possible binary representation of that integer
- concatenate the bits with other encoded numbers

for a more concrete example, if i have the input value `100106`, then I can convert that to a binary string using `format`

```rust
println!("{:b}", 100106_usize);
// "011000011100001010"
```

if I naively convert the `usize` directly to a `BitVec`, then the value is padded

```rust
let bit_vec = BitVec::from_element(100106_usize);
println!("{:b}", bit_vec);
// "[0101000011100001100000000000000000000000000000000000000000000000]"
```

i was playing around with bitwise operators and pushing bits into a `Vec<bool>`. That worked, but felt wrong. I suspect i'm missing something obvious.

Thanks!

**Comment by myrrlyn** [comment]
> though I see the 'discussions' is not enabled

I didn't know that was a thing! I don't keep up to date on GitHub features; I'll start reading about it.

----

On to the question. So. The `::from_element` functions all take the entire register as their length, because there's not really a meaningful way to trim down with the information given. However, you can very easily provide this information: the [`BitView`](https://docs.rs/bitvec/latest/bitvec/view/trait.BitView.html) trait, which is imported in the prelude and implemented on all unsigned integer scalars, arrays, and slices, allows you to convert any of them into an `&BitSlice` view over them. You can then subslice this view into the exact region that you want before copying it into an owned structure.

Currently, it is not possible to truncate `BitArray`s. We're waiting on the next step forward in const generics. This means that you are required to use a heap allocation (`BitVec` or `BitBox`) if you need owned values of arbitrary sizes.

But I digress. The answer is fairly straightforward:

```rust
100106usize
  // View it as bits
  .view_bits::<Lsb0>()
  // only care about the 18 least significant
  [.. 18]
  // and copy em
  .to_bitvec()
```

The end result is an 18-bit-long vector with the desired bit-pattern. Iteration *through* the vector follows [`Lsb0`](https://docs.rs/bitvec/latest/bitvec/order/struct.Lsb0.html) order, but if you were to use the [`BitField`](https://docs.rs/bitvec/latest/bitvec/field/trait.BitField.html) to load the value out of it, `bv.load::<usize>()` would give you `100106usize` right back.

Keep in mind that if you have numbers larger than `bits_of::<usize>()`, `BitField`'s ordering is going to become very important! If you're going to use that trait for complex multi-element storage, you *have* to read its documentation.

Thanks for writing; I hope this correctly answers your question.

**Comment by myrrlyn** [comment]
Oh: you can also find out exactly how many bits you need by taking `100106usize.view_bits::<Lsb0>().iter_ones().last().unwrap()`: this will tell you the bit index (counting from least-significant as zero) of the most-significant `1` bit (16). Add one (17) and that's your range:

```rust
use bitvec::prelude::*;

let num = 100_106usize;
let raw = num.view_bits::<Lsb0>();
let bits = raw.iter_ones().last().unwrap_or(bitvec::mem::bits_of::<usize>() - 1);
let bv = raw[..= bits].to_bitvec();
```

**Comment by danieleades** [comment]
thanks @myrrlyn, that's a massive help. Not sure I would have discovered that on my own.

I think you've pre-empted the next couple of questions I might have too- i will need to store multiple elements, at some point i'm going to need to pad this into a vector of discrete bytes, and I am going to have to be able get the original elements back.

But one thing at a time. Hopefully I can figure the rest out myself. Cheers!
