### ISSUE TITLE
Deserializing with serde yields `invalid type` error

### ISSUE THREAD

**Issue by Nelarius** [bitvecto-rs/bitvec#167]
Hello!

I just started using `bitvec`, thanks for the really cool project! I learned a great deal by reading the documentation. 🙌  

As a fairly novice user of Rust still, I'm stumped with the following behaviour I ran into. Serializing a BitVec to a file, and deserializing from the file yields an ` invalid type: string "order", expected a borrowed string at ...` error. Here's the smallest program that reproduces the issue for me:

```rust
use anyhow::{Context, Result};
use bitvec::prelude::*;
use serde::{Deserialize, Serialize};
use std::fs::File;
use std::path::Path;

#[derive(Serialize, Deserialize, PartialEq, Debug)]
struct Bits(BitVec);

impl Bits {
    fn new() -> Self {
        let bits = bitvec![0, 1, 1, 0, 1, 0, 0, 1];
        Self(bits)
    }
}

fn main() -> Result<()> {
    let bits = Bits::new();
    let file_path = Path::new("bits.json");

    {
        let writer = File::create(&file_path).unwrap();

        serde_json::to_writer(writer, &bits).unwrap();
    }

    {
        let reader = File::open(file_path).unwrap();
        let decoded: Bits = serde_json::from_reader(reader)
            .with_context(|| format!("Deserializing from {}", file_path.display()))?;

        assert_eq!(bits, decoded);
    }

    Ok(())
}
```

I expected the deserialization to succeed, yielding an identical `Bits` instance as the one serialized. I've tried this with both `serde_json` and `bincode`, and observed the same result.

I'm still getting smacked around the compiler a lot, so I am actually not quite sure if the issue is on my end or not 😅

**Comment by jsdw** [comment]
This is a "real" bug I think.

I've run into this as well, both using `serde_json` and `serde_value`. The minimal reproduction is something like:

```rust
use bitvec::{ bitvec, order::Lsb0, vec::BitVec };
use serde::Deserialize;

let original = bitvec![u8, Lsb0; 0, 1, 1, 0, 0, 1, 1, 1, 0];
let json = serde_json::to_value(&original).unwrap();
let out = BitVec::<u8, Lsb0>::deserialize(json);

assert_eq!(out.unwrap(), original);
```

And the error encountered is:

```
'serde_impls::serialize::test::serialize_bitvec' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: string \"bits\", expected a borrowed string", line: 0, column: 0)
```

Serializing is fine, but if we serialize to owned structs, we don't have any borrowed strings.

When we come to deserialize, I think the issue is that the `BitSeqVisitor` attempts, in these cases, to `visit_map`, which asks for borrowed map keys with `map.next_key::<&'de str>()?`. The impl for eg `serde_json` which hand backs keys and values from the map won't be able to provide borrowed keys, so it blows up with an error.

I wonder whether the fix is as simple as changing the `next_key` to something like `map.next_key::<Cow<'de,str>>()?`, which may be able to properly accomodate owned or borrowed strings.

Serde breaks my brain a little though, so I'd have to play around more to know any better!
