### ISSUE TITLE
Bitwise binary operators needlessly slow?

### ISSUE THREAD

**Issue by orlp** [bitvecto-rs/bitvec#89]
Just from reading the source code, I see two problems with the bitwise binary operators (`&`, `|`, `^`).

1. The assign variants do not support a reference RHS. So if you want to compute `a ^= &b` where a, b are bitvecs a needless clone is necessary.

2. As far as I can see, the implementation calls down to the incredibly slow bitwise iterator approach. When you have two bitvecs with the same underlying storage you can directly `&`/`|`/`^` the limbs and get a 8 to 64 times speedup (depending on the size of your limbs).

**Comment by myrrlyn** [comment]
This is a mixture of limitations in the language and underexploration of the design on my part. It is eligible for performance acceleration, at the cost of generality both on Rust's end and on mine. However, it is probably more important to accelerate the common case of operating between like-kinded data structures than it is to enable operating with arbitrary iterators.

**Comment by myrrlyn** [comment]
This acceleration is feasible, but breaks public API. Since I consider performance in the common cases to be an important factor in crate behavior, and we are still in the `0.X` development series, I will do this break.

Please see the branch `feature/better-bitops` for a draft implementation. *Especially* please patch your `Cargo.toml` to use it:

```toml
[patch.crates-io.bitvec]
git = "https://github.com/myrrlyn/bitvec
branch = "feature/better-bitops"
```

I am *not* confident that my implementation is correct, or that I have a satisfactory test suite to find edge cases. I have had defect reports in the past from attempting to try this specialization route, and I would like to test this in the wild before publishing.

Once I am confident in the implementation, I will publish this as a **patch version**, not as `0.21`. While this is technically a semver breaking change, I strongly suspect that nobody is using the APIs that will produce a compile failure, and I have a simple fix for them if I'm wrong.

**Comment by myrrlyn** [comment]
The v1 series replaces the bit-wise operator implementations with batched integer operations. I apologize for completely forgetting to follow up on this in the past ... year ... but it's been a rough one and I haven't been working on `bitvec` as much as I'd have liked.

Anyway. Thanks for prompting me to do this. As the behavior is present in current v1 code, I'm going to close this issue. *Please* feel free to re-open it, or file a new one, if you experience any problems with the code. While I have some tests for it, I am never confident that I have enough, and real-world usage is always more useful than what I am able to contrive myself.
