### ISSUE TITLE
Add `static_bits` as a way to create an &'static BitSlice

### ISSUE THREAD

**Issue by Lucretiel** [bitvecto-rs/bitvec#97]
I have a need in my application for a static `bitvec` type, and it was mentioned on twitter that there used to be such a capability for `BitSlice` that was since removed.

**Comment by myrrlyn** [comment]
Commit a8a4914 merges in support for `bitarr!(const …)` and `bits!(static [mut] …)`. These expansions are able to be used in `const` and `static` bindings (`bitarr!`) or to produce `&'static [mut]` references (`bits!`).

It is currently impossible to produce `static _: &'static BitSlice` references, because borrowing a `BitArray` requires non-constant work. This is a result of *several* limitations:

- type-level integers cannot be used in any computations
- slice handle constructors are not `const fn`
- traits cannot have `const fn`

Use `bitarr!(const)` to create a `const` or `static` name, and then borrow it to the correct length in runtime scopes.
